CREATE TABLE [dbo].[BaseDetails] (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ApplicationNo NVARCHAR(50) NOT NULL,
    SourcingId UNIQUEIDENTIFIER NOT NULL,
    TotalCommAmt DECIMAL(18,2) NULL,
    TotalCommReceived DECIMAL(18,2) NULL,
    BaseCommAmt DECIMAL(18,2) NULL,
    TdsAmount DECIMAL(18,2) NULL,
    AmountClaimed DECIMAL(18,2) NULL,
    AmountReceived DECIMAL(18,2) NULL,
    BasePending DECIMAL(18,2) NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    UpdatedDate DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL
);