CREATE TABLE dbo.Forms (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ClientId UNIQUEIDENTIFIER NULL,
    FormName NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Forms_Client FOREIGN KEY (ClientId) REFERENCES dbo.Clients(ClientId)
);
GO