CREATE TABLE [dbo].[PayoutDetails] (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ApplicationNo NVARCHAR(50) NOT NULL,
    SourcingId UNIQUEIDENTIFIER NOT NULL,
    PayoutPercentage DECIMAL(5,2) NULL,
    PayoutMonth NVARCHAR(50) NULL,
    PayoutAmount DECIMAL(18,2) NULL,
    TdsDeducted DECIMAL(18,2) NULL,
    NetPayoutAmount DECIMAL(18,2) NULL,
    AmountPaid DECIMAL(18,2) NULL,
    BalancePayable DECIMAL(18,2) NULL,
    PayoutStatus NVARCHAR(50) NULL,
    PaidDate DATE NULL,
    PayeeName NVARCHAR(100) NULL,
    PaymentMode NVARCHAR(50) NULL,
    BankAccountNo NVARCHAR(50) NULL,
    BankHolderName NVARCHAR(100) NULL,
    BankName NVARCHAR(100) NULL,
    IfscCode NVARCHAR(20) NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    UpdatedDate DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_PayoutDetails_Sourcing FOREIGN KEY (SourcingId) REFERENCES SourcingDetails(Id),
    CONSTRAINT FK_PayoutDetails_ApplicationNo FOREIGN KEY (ApplicationNo) REFERENCES SourcingDetails(ApplicationNo)
);