CREATE TABLE dbo.Sections (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ClientId UNIQUEIDENTIFIER NULL,
    FormId UNIQUEIDENTIFIER NOT NULL,
    SectionName NVARCHAR(200) NOT NULL,
    DisplayOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Sections_Form FOREIGN KEY (FormId) REFERENCES dbo.Forms(Id),
    CONSTRAINT FK_Sections_Client FOREIGN KEY (ClientId) REFERENCES dbo.Clients(ClientId)
);
GO