CREATE TABLE [dbo].[UserMenu]
(
	UserMenuId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    MenuName NVARCHAR(100) NOT NULL,
    Visible BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (UserId) REFERENCES ClientUser(UserId)
)
